### ISSUE TITLE
版本1.2.0，一直提示用户名和密码错误，是什么原因

### ISSUE THREAD

**Issue by glovanni** [chen310/plugin.audio.music163#1]
一开始安装的1.1.0，可以播放排行榜，成功登陆后，更新成1.2.0了，然后就一直提示用户名密码错误，而且排行榜也刷不出来了，什么原因？

**Comment by glovanni** [comment]
已经关闭登陆保护了还是不行

**Comment by glovanni** [comment]
卸载kodi后，重新安装1.1.0后可以正常用了

**Comment by glovanni** [comment]
卸载kodi后重新安装，先安装1.2.0不能正常用，然后再重新安装1.1.0后好使了

**Comment by glovanni** [comment]
1.2.0在Windows上也不能正确运行

**Comment by glovanni** [comment]
Windows上显示以下错误日志
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'hasMore'
Traceback (most recent call last):
 File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.audio.music163\addon.py", line 1817, in <module>
   plugin.run()
 File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 338, in run
   items = self._dispatch(self.request.path)
 File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 312, in _dispatch
   listitems = view_func(**items)
 File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.audio.music163\addon.py", line 704, in top_mvs
   more = result['hasMore']
KeyError: 'hasMore'
-->End of Python script error report<--

**Comment by kmyqchy** [comment]
kodi18.9 插件13一直密码错误，已经确认网页可以正常登录

**Comment by chen310** [comment]
@glovanni @kmyqchy 更新了，试试能不能行

**Comment by kmyqchy** [comment]
> @glovanni @kmyqchy 更新了，试试能不能行

可以了，非常感谢
